version: '3.6'
services:
  arte-server:
    build: .
    ports:
     - "80:80"
     - "9229:9229"
    volumes:
     - ./data:/arte-server/data
    environment:
     - HOST=0.0.0.0
     - MONGO_URL=mongodb://admin:admin@mongo/admin
  mongo:
    image: "mongo:3.4-jessie"
    ports:
     - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin      
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./data/db:/data/db
